# --------------------------------------
#  Generated by koksmat
# --------------------------------------


#--------------------------------------
# /Users/nielsgregersjohansen/kitchens/docs/scripts/documentation/build-docs/.env
#--------------------------------------
$env:DOC_ORG = "koksmat-com"
$env:DOC_REPO = "koksmat-captain"

#--------------------------------------
#  End of .env files
#
#  Applying Additional settings
# 
#--------------------------------------
$env:WORKDIR = "/Users/nielsgregersjohansen/kitchens/docs/.koksmat/workdir"
Write-Host "WORKDIR: $workdir"

